[project]
name = "codigos-qr1"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "pillow>=11.1.0",
    "pywin32==310",
    "pyzbar>=0.1.9",
    "qrcode>=8.1",
]
